export function formatINR(amount: number): string {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    maximumFractionDigits: 0,
  }).format(amount);
}

export function formatDate(dateStr: string): string {
  if (!dateStr) return '—';
  const parsed = new Date(dateStr);
  if (isNaN(parsed.getTime())) return dateStr;
  return parsed.toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  });
}

export function triggerDummyDownload(filename: string, title: string, metadata?: Record<string, string>) {
  const cleanName = filename.split('/').pop() || 'gram-panchayat-record.pdf';
  const lines = [
    '====================================================================',
    '            GRAM PANCHAYAT LAKHLGOAN (ग्रामपंचायत लाखलगाव)            ',
    '          DIGITAL RECORDS & CITIZEN DOCUMENT PORTAL (DEMO)          ',
    '====================================================================',
    '',
    `Document Title : ${title}`,
    `File Reference : ${cleanName}`,
    `Generated On   : ${new Date().toLocaleString('en-IN')}`,
    'Status         : Certified Digital Copy (Academic Prototype)',
    '',
  ];

  if (metadata) {
    Object.entries(metadata).forEach(([k, v]) => {
      lines.push(`${k.padEnd(15, ' ')}: ${v}`);
    });
    lines.push('');
  }

  lines.push(
    '--------------------------------------------------------------------',
    'NOTE: This file is generated by the Lakhlgoan Gram Panchayat Digital',
    'Records Portal prototype for academic demonstration purposes.',
    '===================================================================='
  );

  const blob = new Blob([lines.join('\n')], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = cleanName.endsWith('.pdf') || cleanName.endsWith('.xlsx') ? `${cleanName}.txt` : cleanName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportToCSV(filename: string, headers: string[], rows: (string | number)[][]) {
  const csvContent = [
    headers.join(','),
    ...rows.map((row) =>
      row
        .map((cell) => {
          const str = String(cell ?? '').replace(/"/g, '""');
          return `"${str}"`;
        })
        .join(',')
    ),
  ].join('\n');

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename.endsWith('.csv') ? filename : `${filename}.csv`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
